name: codelab_builders
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  analyzer: ^7.4.0
  build: ^2.4.2
  dart_style: ^3.0.0
  glob: ^2.0.0

dependency_overrides:
  build:
    path: ../../../build
  build_config:
    path: ../../../build_config
  build_runner_core:
    path: ../../../build_runner_core
