builders:
  many_files_builder:
    import: "package:codelab_builders/builders.dart"
    builder_factories: ["equalityBuilder"]
    build_extensions: {".dart": [".equality.dart"]}
    build_to: source
    auto_apply: dependents