name: build_analyzer_plugin
version: 0.0.1-wip
description: Analyzer plugin for build_runner.
repository: https://github.com/dart-lang/build/tree/master/build_analyzer_plugin
resolution: workspace
publish-to: none

environment:
  sdk: ^3.10.0

platforms:
  linux:
  windows:
  macos:

dependencies:
  analysis_server_plugin: any
#    path: ../../../git/dart-sdk/sdk/pkg/analysis_server_plugin
  analyzer: any
#    path: ../../../git/dart-sdk/sdk/pkg/analyzer
  analyzer_plugin: any
#    path: ../../../git/dart-sdk/sdk/pkg/analyzer_plugin

topics:
 - build-runner

dependency_overrides:
#  analysis_server_plugin:
#    path: ../../../git/dart-sdk/sdk/pkg/analysis_server_plugin
#  analyzer:
#    path: ../../../git/dart-sdk/sdk/pkg/analyzer
#  analyzer_plugin:
#    path: ../../../git/dart-sdk/sdk/pkg/analyzer_plugin
